### ISSUE TITLE
No node type or group 'undefined' found 

### ISSUE THREAD

**Issue by MichaelKheel** [michelson/Dante#222]
```js
index.es.js:1640 Uncaught SyntaxError: No node type or group 'undefined' found (in content expression 'undefined+')
    at TokenStream.err (index.es.js:1640:56)
    at resolveName (index.es.js:1699:36)
    at parseExprAtom (index.es.js:1709:17)
    at parseExprSubscript (index.es.js:1659:14)
    at parseExprSeq (index.es.js:1653:19)
    at parseExpr (index.es.js:1646:19)
    at Function.parse (index.es.js:1474:14)
    at new Schema (index.es.js:2359:53)
    at getSchemaByResolvedExtensions (tiptap-core.esm.js:2661:12)
    at new ExtensionManager (tiptap-core.esm.js:2677:23)
    at Editor.createExtensionManager (tiptap-core.esm.js:3140:33)
    at new Editor (tiptap-core.esm.js:3009:14)
    at new Editor (tiptap-react.esm.js:59:9)
    at eval (tiptap-react.esm.js:98:26)
    at invokePassiveEffectCreate (react-dom.development.js:23482:20)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:16)
    at invokeGuardedCallback (react-dom.development.js:4056:31)
    at flushPassiveEffectsImpl (react-dom.development.js:23569:9)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushPassiveEffects (react-dom.development.js:23442:14)
    at performSyncWorkOnRoot (react-dom.development.js:22264:3)
    at eval (react-dom.development.js:11327:26)
    at unstable_runWithPriority (scheduler.development.js:468:12)
    at runWithPriority$1 (react-dom.development.js:11276:10)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11322:9)
    at flushSyncCallbackQueue (react-dom.development.js:11309:3)
    at batchedUpdates$1 (react-dom.development.js:22382:7)
    at reactionScheduler (mobx.esm.js:2757:12)
    at runReactions (mobx.esm.js:2726:3)
    at endBatch (mobx.esm.js:2346:5)
    at _endAction (mobx.esm.js:1387:3)
    at executeAction (mobx.esm.js:1331:5)
    at <unnamed action> (mobx.esm.js:1310:12)
    at runMiddleWares (mobx-state-tree.module.js:3336:73)
    at runWithActionContext (mobx-state-tree.module.js:3179:16)
    at wrap (mobx-state-tree.module.js:4491:13)
    at onFulfilled (mobx-state-tree.module.js:4505:21)
```

```jsx
import Dante from 'dante3';

export default function News() {
    return(
        <div>
        <Dante content={`test`} />
        </div>
    )
}
```

```json
  "dependencies": {
    "@emotion/cache": "^11.7.1",
    "@emotion/react": "^11.8.2",
    "@emotion/server": "^11.4.0",
    "@emotion/styled": "^11.8.1",
    "@fontsource/roboto": "^4.5.3",
    "@mui/codemod": "^5.5.1",
    "@mui/icons-material": "^5.5.1",
    "@mui/lab": "^5.0.0-alpha.73",
    "@mui/material": "^5.5.1",
    "@mui/styles": "^5.5.1",
    "@mui/x-data-grid": "^5.7.0",
    "axios": "^0.26.1",
    "dante3": "^1.0.8",
    "mobx": "^6.5.0",
    "mobx-react-lite": "^3.3.0",
    "mobx-state-tree": "^5.1.3",
    "mobx-utils": "^6.0.4",
    "moment": "^2.29.1",
    "next": "12.1.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-moment": "^1.1.1",
    "store": "^2.0.12"
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.16.7",
    "@types/node": "^17.0.21",
    "babel-plugin-transform-imports": "^2.0.0",
    "eslint": "8.11.0",
    "eslint-config-next": "12.1.0"
  }
```

**Comment by thomas-weiland** [comment]
Same... Is there a solution yet?

**Comment by michelson** [comment]
use latest version
