### ISSUE TITLE
Dante3 not working with vite

### ISSUE THREAD

**Issue by wandersonalwes** [michelson/Dante#257]
I get this error

```shell
✘ [ERROR] Could not resolve "prosemirror-history"

    node_modules/@tiptap/extension-history/dist/tiptap-extension-history.esm.js:2:36:
      2 │ import { undo, redo, history } from 'prosemirror-history';
        ╵                                     ~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "prosemirror-history" as external to exclude it from the bundle, which will
  remove this error.

✘ [ERROR] Could not resolve "prosemirror-gapcursor"

    node_modules/@tiptap/extension-gapcursor/dist/tiptap-extension-gapcursor.esm.js:2:26:
      2 │ import { gapCursor } from 'prosemirror-gapcursor';
        ╵                           ~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "prosemirror-gapcursor" as external to exclude it from the bundle, which
  will remove this error.

✘ [ERROR] Could not resolve "prosemirror-dropcursor"

    node_modules/@tiptap/extension-dropcursor/dist/tiptap-extension-dropcursor.esm.js:2:27:
      2 │ import { dropCursor } from 'prosemirror-dropcursor';
        ╵                            ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "prosemirror-dropcursor" as external to exclude it from the bundle, which
  will remove this error.

/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1575
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 3 errors:
node_modules/@tiptap/extension-dropcursor/dist/tiptap-extension-dropcursor.esm.js:2:27: ERROR: Could not resolve "prosemirror-dropcursor"
node_modules/@tiptap/extension-gapcursor/dist/tiptap-extension-gapcursor.esm.js:2:26: ERROR: Could not resolve "prosemirror-gapcursor"
node_modules/@tiptap/extension-history/dist/tiptap-extension-history.esm.js:2:36: ERROR: Could not resolve "prosemirror-history"
    at failureErrorWithLog (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1575:15)
    at /Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1033:28
    at runOnEndCallbacks (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1447:61)
    at buildResponseToResult (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1031:7)
    at /Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:1143:14
    at responseCallbacks.<computed> (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:680:9)
    at handleIncomingPacket (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:735:9)
    at Socket.readFromStdout (/Users/wanderson/www/ei/community/dante3/node_modules/esbuild/lib/main.js:656:7)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 27,
        file: 'node_modules/@tiptap/extension-dropcursor/dist/tiptap-extension-dropcursor.esm.js',
        length: 24,
        line: 2,
        lineText: "import { dropCursor } from 'prosemirror-dropcursor';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "prosemirror-dropcursor" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "prosemirror-dropcursor"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 26,
        file: 'node_modules/@tiptap/extension-gapcursor/dist/tiptap-extension-gapcursor.esm.js',
        length: 23,
        line: 2,
        lineText: "import { gapCursor } from 'prosemirror-gapcursor';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "prosemirror-gapcursor" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "prosemirror-gapcursor"'
    },
    {
      detail: undefined,
      id: '',
      location: {
        column: 36,
        file: 'node_modules/@tiptap/extension-history/dist/tiptap-extension-history.esm.js',
        length: 21,
        line: 2,
        lineText: "import { undo, redo, history } from 'prosemirror-history';",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "prosemirror-history" as external to exclude it from the bundle, which will remove this error.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "prosemirror-history"'
    }
  ],
  warnings: []
}
```

I tried it

```shell
yarn add prosemirror-dropcursor prosemirror-gapcursor prosemirror-history
```

but i get this other error

![Captura de Tela 2022-12-07 às 12 06 47](https://user-images.githubusercontent.com/19822794/206215157-c44461c7-eac2-4bea-896f-6d57284585ae.png)

https://codesandbox.io/s/dante3-with-vite-olulg6

**Comment by wandersonalwes** [comment]
This happens in newer versions of tiptap

**Comment by michelson** [comment]
Can you provide more information. Dante3 has fixed versions of tiptap are
you using those? Which version of dante3 are you using? Can you provide a
failing example in code sandbox?

**Comment by michelson** [comment]
which versions are you using? is not easy to follow what is not working here.
I have dante3 up and running in other projects so not sure if you are using the same versions.
this is what Dante3 uses when you install it.
![image](https://user-images.githubusercontent.com/11976/206779323-000136ef-3988-4c5b-a1c1-095726f786f3.png)

**Comment by michelson** [comment]
also, the latest version is 1.1.6

**Comment by wandersonalwes** [comment]
@michelson 
![Captura de Tela 2022-12-09 às 17 32 26](https://user-images.githubusercontent.com/19822794/206791365-3734a025-540a-4457-bd5e-332a2cffe182.png)

**Comment by wandersonalwes** [comment]
Solution #259 worked for me, so I'm closing this issue.
